#!/bin/bash
# script to git repositories for the Rodney Robot project, with the exception of the rodney package.
# run the script (./clonepackages) from a clone of the rodney package
cd ..
git clone https://github.com/phopley/servo_msgs.git
git clone https://github.com/phopley/pan_tilt.git
git clone https://github.com/phopley/face_recognition_msgs.git
git clone https://github.com/phopley/face_recognition.git
git clone https://github.com/phopley/head_control.git
git clone https://github.com/lrse/ros-keyboard.git

