#!/bin/bash
# script to create symbolic links from git folders to rodney_ws for Rodney Robot project
# run ./createlinks
ln -s /mnt/git/face_recognition ~/rodney_ws/src
ln -s /mnt/git/face_recognition_msgs ~/rodney_ws/src
ln -s /mnt/git/head_control ~/rodney_ws/src
ln -s /mnt/git/git/joystick ~/rodney_ws/src
ln -s /mnt/git/pan_tilt ~/rodney_ws/src
ln -s /mnt/git/rodney ~/rodney_ws/src
ln -s /mnt/git/rodney_missions ~/rodney_ws/src
ln -s /mnt/git/ros-keyboard ~/rodney_ws/src
ln -s /mnt/git/servo_msgs ~/rodney_ws/src
ln -s /mnt/git/speech ~/rodney_ws/src
ln -s /mnt/git/tf_object_detection ~/rodney_ws/src
