#!/bin/bash
# script to create symbolic links from git folders to catkin_ws for Rodney Robot project
# run ./creatlinks
ln -s ~/git/rodney ~/catkin_ws/src
ln -s ~/git/face_recognition ~/catkin_ws/src
ln -s ~/git/face_recognition_msgs ~/catkin_ws/src
ln -s ~/git/head_control ~/catkin_ws/src
ln -s ~/git/pan_tilt ~/catkin_ws/src
ln -s ~/git/servo_msgs ~/catkin_ws/src
ln -s ~/git/ros-keyboard ~/catkin_ws/src



