move_base:
  controller_frequency: 1.4
  TrajectoryPlannerROS:
    holonomic_robot: false
    meter_scoring: true
    max_vel_x: 0.25
    min_vel_x: 0.17
    escape_vel: -0.2
    max_vel_theta: 1.5
    min_vel_theta: -1.5
    min_in_place_vel_theta: 1.2
     
    

    
