controller_frequency: 1.5  # Can we move this back to 5.0 if using different Pi
use_grid_path: true
base_global_planner: global_planner/GlobalPlanner
base_local_planner: dwa_local_planner/DWAPlannerROS
DWAPlannerROS:
  acc_lim_x: 1.0                      # def 2.5
  acc_lim_y: 0.0                      # def 2.5
  acc_lim_theta: 1.5                  # def 3.2           wiki calls it acc_lim_th but it is acc_lim_theta
  acc_lim_trans: 1.0                  # def 0.1           not in the wiki
  max_trans_vel: 0.25                 # def 0.55
  min_trans_vel: 0.16                 # def 0.1
  max_vel_x: 0.25                     # def 0.55          The maximum foward velocity
  min_vel_x: -0.16                    # def 0.0           Too high a value robot will travel backwards a long way
  max_vel_y: 0.0                      # def 0.1
  min_vel_y: 0.0                      # def -0.1
  max_rot_vel: 1.5                    # def 1.0
  min_rot_vel: 1.3                    # def 0.4           
  yaw_goal_tolerance: 0.3             # def 0.05
  xy_goal_tolerance: 0.25             # def 0.10
  sim_time: 3.0                       # def 1.7
  sim_granularity: 0.1                # def 0.025
  vx_samples: 20                      # def 3
  vy_samples: 0                       # def 10
  vth_samples: 40                     # def 20
  path_distance_bias: 34.0            # def 32.0
  goal_distance_bias: 24.0            # 
  occdist_scale: 0.05                 # def 0.01
  forward_point_distance: 0.3         # def 0.325
  stop_time_buffer: 0.5               # def 0.2
  scaling_speed: 0.25                 # 
  max_scaling_factor: 0.2             # 
  oscillation_reset_dist: 0.05        # 
  prune_plane: false                  # def true
    
  trans_stopped_vel: 0.1              #                not in the wiki 
  rot_stopped_vel: 0.1                #                not in the wiki   
  angular_sim_granularity: 0.1        #                not in the wiki     
  twirling_scale: 0.0                 #                not in the wiki
  oscillation_reset_angle: 0.2        #                not in the wiki
  use_dwa: true                       #                not in the wiki


    

    
