controller_frequency: 5.0
use_grid_path: true
base_global_planner: global_planner/GlobalPlanner
base_local_planner: dwa_local_planner/DWAPlannerROS
DWAPlannerROS:
  acc_lim_x: 0.75
  acc_lim_y: 0.0
  acc_lim_theta: 1.75                 # wiki calls it acc_lim_th but it is acc_lim_theta
  acc_lim_trans: 1.0
  max_trans_vel: 0.25
  min_trans_vel: 0.1
  max_vel_x: 0.25                     # The maximum foward velocity
  min_vel_x: -0.1
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_rot_vel: 2.5
  min_rot_vel: 0.3
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.25
  sim_time: 2.0
  sim_granularity: 0.1
  vx_samples: 3
  vy_samples: 10
  vth_samples: 20
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.05
  forward_point_distance: 0.3
  stop_time_buffer: 0.5
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  oscillation_reset_dist: 0.05
  prune_plan: true
    
  trans_stopped_vel: 0.1
  rot_stopped_vel: 0.1 
  angular_sim_granularity: 0.1    
  twirling_scale: 0.0
  oscillation_reset_angle: 0.2
  use_dwa: true


    

    
