move_base:
  controller_frequency: 2.0
  planner_frequency: 1.0 # Not sure this is in the right place or exists
  TrajectoryPlannerROS:
    holonomic_robot: false
    meter_scoring: true
    max_vel_x: 0.25
    min_vel_x: 0.02
    escape_vel: -0.1
    max_vel_theta: 1.5
    min_vel_theta: -1.5
    
     
    

    
