obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.170, 0.145], [-0.170, 0.145], [-0.170, -0.145], [0.170, -0.145]] # Simple rectangle taking in the base and wheels
inflation_radius: 0.55
observation_sources: laser_scan_sensor
laser_scan_sensor:
  sensor_frame: laser
  data_type: LaserScan
  topic: scan
  marking: true
  clearing: true
