local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  static_map: false
  rolling_window: true
  transform_tolerance: 1.0
  update_frequency: 1.0
  publish_frequency: 0.5
  width: 2.5
  height: 2.5


