move_base:
  local_costmap:
    global_frame: odom
    robot_base_frame: base_link
    static_map: false
    rolling_window: true
    transform_tolerance: 0.7 # Still investigating
    update_frequency: 1.0
    publish_frequency: 0.5


